#!/bin/sh -e

ostype=debian

# Fixup for RedHat/CentOS calling conventions
arg=$1
case $arg in
        0) arg=purge ; ostype=redhat ;;
        1) arg=upgrade ; ostype=redhat ;;
esac

if [ "$arg" = "purge" ] ; then
	if [ -d /var/lib/rudder-backup ]; then
		echo "Removing /var/lib/rudder-backup ..."
		rm -rf /var/lib/rudder-backup
	fi
	if [ -d /var/backups/rudder-backup ]; then
		echo "Removing /var/backups/rudder-backup ..."
		rm -rf /var/backups/rudder-backup
	fi
fi
